/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 robot.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.main_column.geometry} material={nodes.main_column.material} position={[0, 1.462, 0]} />
      <mesh geometry={nodes.upper_arm.geometry} material={nodes.upper_arm.material} position={[2.335, 0, 0.094]} scale={[0.684, 1, 1]} />
      <mesh geometry={nodes.elbow.geometry} material={nodes.elbow.material} position={[2.6, 5.933, 0.074]} scale={[0.345, 0.122, 0.345]} />
      <mesh geometry={nodes.lower_arm.geometry} material={nodes.lower_arm.material} position={[4.39, -0.984, 0.094]} scale={[0.684, 1, 1]} />
      <mesh geometry={nodes.wrist.geometry} material={nodes.wrist.material} position={[4.701, 4.949, 0.101]} scale={[0.345, 0.122, 0.345]} />
      <mesh geometry={nodes.wrist_extension.geometry} material={nodes.wrist_extension.material} position={[4.691, 4.611, 0.007]} scale={0.264} />
      <mesh geometry={nodes.hand.geometry} material={nodes.hand.material} position={[5.368, 3.78, 0.049]} scale={[1, 0.068, 0.327]} />
      <mesh geometry={nodes.gripper.geometry} material={nodes.gripper.material} position={[5.805, 3.585, 0.006]} rotation={[-Math.PI, 0, 0]} scale={[-0.01, -0.132, -0.325]} />
    </group>
  )
}

useGLTF.preload('/robot.glb')
